name = "khtyvolyandia-bot"
main = "dist/index.js"
compatibility_date = "2023-07-05"
no_bundle = true

[triggers]
crons = ["*/30 * * * *"]

[[rules]]
type = "Text"
globs = ["**/*.yml", "**/*.map"]
fallthrough = true

[build]
command = "yarn node build"
