name: Check the bot

on:
  pull_request:

jobs:
  build-check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check actual build & type errors with TSC
        run: yarn run tsc
